### ISSUE TITLE
Problem startup chart

### ISSUE THREAD

**Issue by kfirfer** [aleveille/octant-dashboard-turnkey#2]
Using kubernetes 1.18.6

This part of the logs from the container:

```
goroutine 49 [chan receive]:
github.com/vmware-tanzu/octant/pkg/plugin/api.(*grpcAPI).Start.func2(0x2cb3a20, 0xc0004fe150, 0x2cc4100, 0xc00011a9e8, 0xc000602600)
        /__w/octant/octant/pkg/plugin/api/api.go:68 +0x4c
created by github.com/vmware-tanzu/octant/pkg/plugin/api.(*grpcAPI).Start
        /__w/octant/octant/pkg/plugin/api/api.go:67 +0x196

goroutine 50 [select]:
github.com/vmware-tanzu/octant/pkg/plugin.(*Manager).watchPlugins(0xc000216ab0, 0x2cb3a20, 0xc0004fe150)
        /__w/octant/octant/pkg/plugin/manager.go:316 +0x49a
created by github.com/vmware-tanzu/octant/pkg/plugin.(*Manager).Start
        /__w/octant/octant/pkg/plugin/manager.go:304 +0x325

goroutine 74 [IO wait]:
internal/poll.runtime_pollWait(0x7f705a6d8d80, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000272398, 0x72, 0x2400, 0x242c, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000272380, 0xc000524000, 0x242c, 0x242c, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000272380, 0xc000524000, 0x242c, 0x242c, 0x203000, 0x675cb0, 0xc00019e138)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0001ac088, 0xc000524000, 0x242c, 0x242c, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc00026e2e0, 0xc000524000, 0x242c, 0x242c, 0x1a, 0xaac, 0xc0006a99c8)
        /usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc00019e258, 0x2c72d40, 0xc00026e2e0, 0x40a1b5, 0x17a6ba0, 0x192c740)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00019e000, 0x2c75600, 0xc0001ac088, 0x5, 0xc0001ac088, 0x9)
        /usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc00019e000, 0x0, 0x0, 0xc0006a9d38)
        /usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc00019e000, 0xc00017f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc0002c9aa0, 0xc000240118, 0x9, 0x9, 0xc0006a9d38, 0x2aa6c00, 0x972c72)
        /usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x2c72ba0, 0xc0002c9aa0, 0xc000240118, 0x9, 0x9, 0x9, 0xc000184110, 0x0, 0x2c73080)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc000240118, 0x9, 0x9, 0x2c72ba0, 0xc0002c9aa0, 0x0, 0x0, 0xc0002704e0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0002400e0, 0xc0002704e0, 0x0, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0006a9fa8, 0xc000097fb0, 0x7605f2)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/transport.go:1679 +0x8d
golang.org/x/net/http2.(*ClientConn).readLoop(0xc00068b080)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/transport.go:1607 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /go/pkg/mod/golang.org/x/net@v0.0.0-20190812203447-cdfb69ac37fc/http2/transport.go:670 +0x64a
```

**Comment by aleveille** [comment]
I'll see if I can reproduce. The stack trace from Octant doesn't look like it's giving me much to work with, but I'll look into it nonetheless

**Comment by aleveille** [comment]
I was able to start the chart successfully on a Kubespray cluster with versions `v1.18.5` and `v1.18.6`.

Some questions:
- How is your cluster provisioned (GKE, AKS, EKS, Kubespray, KOPS, other)?
- How is your cluster configured (CNI, etc)?
- Are you using a values.yaml file? 
- Which namespace are your deploying to? (Can you share your install command)

**Comment by kfirfer** [comment]
Cluster provisioned with kubeadm
Kubernetes 1.18.8
Using ubuntu 20.04.01
Docker version 19.03.12, build 48a66213fe
Calico as network
topolvm as storage provisioner


Installed via Helm v3.2.4
This is the command used:
```
helm upgrade -i octant octant --namespace=octant --create-namespace
```

**Comment by kfirfer** [comment]
One more part from the logs:

```
[octant-757f97976b-sbk64] 2020-08-23T12:27:20.698Z      INFO    dash/watcher.go:116     watching config file    {"component": "config-watcher", "config": "/tmp/kubeconfig"} 
[octant-757f97976b-sbk64] runtime: mlock of signal stack failed: 12 
[octant-757f97976b-sbk64] runtime: increase the mlock limit (ulimit -l) or 
[octant-757f97976b-sbk64] runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+ 
[octant-757f97976b-sbk64] fatal error: mlock failed 
[octant-757f97976b-sbk64]  
[octant-757f97976b-sbk64] runtime stack: 
[octant-757f97976b-sbk64] runtime.throw(0x19a5881, 0xc) 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/panic.go:1112 +0x72 
[octant-757f97976b-sbk64] runtime.mlockGsignal(0xc000103080) 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/os_linux_x86.go:72 +0x107 
[octant-757f97976b-sbk64] runtime.mpreinit(0xc000840000) 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/os_linux.go:341 +0x78 
[octant-757f97976b-sbk64] runtime.mcommoninit(0xc000840000) 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/proc.go:630 +0x108 
[octant-757f97976b-sbk64] runtime.allocm(0xc00005f000, 0x2aa6b40, 0x0) 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/proc.go:1390 +0x14e 
[octant-757f97976b-sbk64] runtime.newm(0x2aa6b40, 0xc00005f000) 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/proc.go:1704 +0x39 
[octant-757f97976b-sbk64] runtime.startm(0x0, 0xc00043b501) 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/proc.go:1869 +0x12a 
[octant-757f97976b-sbk64] runtime.wakep(...) 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/proc.go:1953 
[octant-757f97976b-sbk64] runtime.resetspinning() 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/proc.go:2415 +0x93 
[octant-757f97976b-sbk64] runtime.schedule() 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/proc.go:2527 +0x2de 
[octant-757f97976b-sbk64] runtime.mstart1() 
[octant-757f97976b-sbk64]       /usr/local/go/src/runtime/proc.go:1104 +0x8e
```

**Comment by kfirfer** [comment]
After investigating, this is kernel bug:
https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug

FYI 
This is the version:
Linux nuc01 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aleveille** [comment]
Hi @kfirfer. Thanks for the follow-up! Since this is a kernel/Go go, do you mind opening the bug against [vmware-tanzu/octant](https://github.com/vmware-tanzu/octant/issues) and I'll close this issue?

**Comment by kfirfer** [comment]
Closing
